name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Start docker-compose
        run: sudo docker-compose up -d
      - name: Clean up
        run: sudo docker system prune -f
